In [2]:
import numpy as np

In [10]:
#transforma lista em array
lista = [1,2,3]
np.array(lista)

array([1, 2, 3])

In [11]:
#pode fazer pra listas de listas tambem
matriz = [[1,2,3],[4,5,6],[7,8,9]]
np.array(matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
#arange cria uma sequencia de numeros ja em array
print(np.arange(10))
print(np.arange(1,10))
print(np.arange(1,10,2))

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [16]:
#cria vetor com zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
#para criar matrizes com esse metodo
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
#cria vetor com 1s
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
#o metodo do vetor funciona
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
#cria matriz identidade
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
#metodo lenght in space(linspace) faz numeros igualmente espaçados entre um ponto e outro
np.linspace(0,10,21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [33]:
#cria uma distribuição uniforme entre 0 e 1
np.random.rand(5)

array([[0.14550739, 0.15956687, 0.39081686, 0.89076683, 0.14864158,
        0.60537886, 0.92627751, 0.63504978, 0.22884288, 0.45542704],
       [0.62218582, 0.56318069, 0.64263497, 0.02679028, 0.78313035,
        0.10963718, 0.63955543, 0.56625094, 0.63314273, 0.47331501],
       [0.54569202, 0.66752528, 0.47496031, 0.88010474, 0.49551661,
        0.86399018, 0.36723119, 0.81548774, 0.63292813, 0.84443787],
       [0.55131486, 0.19336061, 0.94440774, 0.42392257, 0.71567258,
        0.61334673, 0.09120092, 0.73430744, 0.91044575, 0.051487  ],
       [0.46266466, 0.20990298, 0.82638092, 0.45133761, 0.76275633,
        0.3757149 , 0.37026048, 0.779704  , 0.18197085, 0.74853399]])

In [35]:
#cria uma distribuição normal entre 0 e 1(gaussiana)
np.random.randn(10)

array([-1.47866887, -0.8403302 , -0.4970784 ,  0.18639407, -1.6635343 ,
        1.58111654,  0.0675612 ,  0.93611461, -0.64047376,  1.37504678])

In [37]:
#cria distribuição uniforme com numeros inteiros, os parametros são minimo,maximo, quantidade
np.random.randint(0,100,10)

array([18, 34, 78, 24, 34,  1, 10, 54, 52, 40])

In [38]:
#arredonda os valores9o segundo paramettro são as casas decimais
np.round(np.random.rand(10),2)

array([0.27, 0.52, 0.55, 0.49, 0.36, 0.32, 0.08, 0.23, 0.49, 0.75])

In [41]:
#transforma em outro formato
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [44]:
#metodo para verificar o tamanho e formato do array
print(np.arange(5).shape)
print(np.zeros((5,5)).shape)

(5,)
(5, 5)


In [57]:
#array para os exemplos seguintes
arr = np.random.rand(10)*100
arr

array([82.01309296,  3.55291777, 43.53508803, 74.70781576, 52.0539894 ,
       95.72539336,  7.84744368, 66.61754906, 29.09899517, 86.61235032])

In [58]:
#retorna o maior valor do array
arr.max()

95.72539335590736

In [59]:
#retorna o menor valor do array
arr.min()

3.5529177698076286

In [60]:
#retorna o inidice do maior elemento
arr.argmax()

5

In [62]:
#retorna o indice do menor elemento
arr.argmin()

1