In [2]:
import numpy as np

In [7]:
arr = np.arange(0,30,3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [4]:
#puxar valor pelo indice
arr[3]

9

In [6]:
#puxar multiplos valores pelo indice
print(arr[2:4])#imprime os elementos 2 e 3
print(arr[:4])#imprime todos os elementos até q o indice seja 4
print(arr[2:])#imprime todos os elementos a partir do indice 2

[6 9]
[0 3 6 9]
[ 6  9 12 15 18 21 24 27]


In [10]:
#é possivel ALTERAR multiplos valores de uma vez também
arr[4:] = 100
arr


array([  0,   3,   6,   9, 100, 100, 100, 100, 100, 100])

In [10]:
#funciona para vetores com mais de uma dimensão também
arr = np.arange(50).reshape(5,10)
arr[:][:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [15]:
#Esse comando cria uma referência, e não uma copia, portanto qualquer alteração em arr2 também alterará arr
arr2 = arr[:3]
arr2[:] = 100
arr

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [16]:
#Esse comando gera uma copia
arr = np.arange(50).reshape(5,10)
arr2 = arr[3:].copy()
arr2[:] = 100
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [18]:
#para obter slices das matrizes usamos a notação a seguir
arr[:3,4:]

array([[ 4,  5,  6,  7,  8,  9],
       [14, 15, 16, 17, 18, 19],
       [24, 25, 26, 27, 28, 29]])

In [24]:
#podemos tambem definir regras para fazer o slice do nosso vetor
bol = arr > 20
print(bol)
arr[bol]

[[False False False False False False False False False False]
 [False False False False False False False False False False]
 [False  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]]


array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [25]:
#podemos passar o parametro diretamente no array
arr[arr>20]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])