In [1]:
import numpy as np

In [2]:
arr = np.arange(20)

In [3]:
#podemos fazer operaçẽs em arrays como se fossem variáveis comuns
#as operações são feitas índice à índice
print(arr + arr)
print(arr*2)
print(arr**3)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]
[   0    1    8   27   64  125  216  343  512  729 1000 1331 1728 2197
 2744 3375 4096 4913 5832 6859]


In [4]:
#podemos fazer operaçoes de arrays com escalares
print(arr + 100)

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119]


In [5]:
#podemos usar em funções como se fossem números
np.sqrt(arr)#raiz quadrada

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894])

In [6]:
np.exp(arr)#exponencial

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [7]:
np.mean(arr)#tira a media do array

9.5

In [8]:
np.std(arr)#desvio padrao

5.766281297335398

In [9]:
np.sin(arr)#função seno(existe cos e tan)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721])